#!/usr/bin/env bash
# DNYFappbuilder — Project Init Script v2.0.0
set -Eeuo pipefail

ABP_ROOT="${ABP_ROOT:-$HOME/dnyf-appbuilder}"
source "$ABP_ROOT/lib/common.sh"

NAME="${1:-myapp}"
TEMPLATE="${2:-react-native}"
DEST="${3:-./$NAME}"

[[ -d "$DEST" ]] && {
    log_error "Directory already exists: $DEST"
    exit 1
}

log_info "Creating project: ${BOLD}$NAME${RESET} ($TEMPLATE)"
timer_start

# ── Common files added to every project ───────────────────
add_common_files() {
    local dir="$1"
    # .gitignore
    cat > "$dir/.gitignore" <<'GIT'
.env
.env.*
*.keystore
*.jks
node_modules/
venv/
__pycache__/
*.pyc
.dart_tool/
build/
dist/
.gradle/
*.log
GIT

    # .editorconfig
    cat > "$dir/.editorconfig" <<'EC'
root = true
[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
EC

    # README
    cat > "$dir/README.md" <<MD
# $NAME

Generated by [DNYFappbuilder](https://github.com/DNYFTECH/dnyf-appbuilder)

## Build

\`\`\`bash
abp build . --target android --profile release
\`\`\`

## Install on Device

\`\`\`bash
abp build . --target android --sign --install
# or after build:
abp install <path-to.apk>
\`\`\`
MD
}

# ── Templates ─────────────────────────────────────────────
case "$TEMPLATE" in

    react-native)
        require node "https://nodejs.org"
        require npx  "comes with npm"
        log_step "Initializing React Native project..."
        npx @react-native-community/cli init "$NAME" --directory "$DEST" --skip-install
        cd "$DEST"
        npm install
        add_common_files .
        ;;

    flutter)
        require flutter "https://flutter.dev"
        log_step "Creating Flutter project..."
        flutter create --project-name "$(echo "$NAME" | tr '-' '_')" "$DEST"
        add_common_files "$DEST"
        ;;

    android)
        log_step "Creating native Android project..."
        mkdir -p "$DEST"
        cd "$DEST"
        mkdir -p app/src/main/{java/com/example/"$(echo "$NAME" | tr '-' '_')",res/{layout,values,drawable}}

        cat > settings.gradle <<GRADLE
pluginManagement {
    repositories { google(); mavenCentral(); gradlePluginPortal() }
}
dependencyResolutionManagement {
    repositories { google(); mavenCentral() }
}
rootProject.name = "$NAME"
include ':app'
GRADLE

        cat > build.gradle <<GRADLE
plugins {
    id 'com.android.application' version '8.1.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.9.0' apply false
}
GRADLE

        cat > app/build.gradle <<GRADLE
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}
android {
    namespace 'com.example.$(echo "$NAME" | tr '-' '_')'
    compileSdk 34
    defaultConfig {
        applicationId "com.example.$(echo "$NAME" | tr '-' '_')"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions { jvmTarget = '1.8' }
}
dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.10.0'
}
GRADLE

        # MainActivity
        cat > "app/src/main/java/com/example/$(echo "$NAME" | tr '-' '_')/MainActivity.kt" <<KOTLIN
package com.example.$(echo "$NAME" | tr '-' '_')

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
    }
}
KOTLIN

        # AndroidManifest
        cat > app/src/main/AndroidManifest.xml <<XML
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:allowBackup="true"
        android:label="$NAME"
        android:theme="@style/Theme.AppCompat.DayNight">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
XML

        cp /usr/local/bin/gradlew . 2>/dev/null || \
        curl -sL https://services.gradle.org/distributions/gradle-8.3-bin.zip -o /tmp/gradle.zip 2>/dev/null || \
        echo "#!/bin/sh" > gradlew && echo "gradle \"\$@\"" >> gradlew
        chmod +x gradlew
        add_common_files .
        ;;

    nodejs)
        log_step "Creating Node.js API project..."
        mkdir -p "$DEST"/{src,tests}
        cd "$DEST"
        npm init -y --silent

        npm install express cors dotenv helmet morgan express-rate-limit --save --silent
        npm install nodemon jest --save-dev --silent

        # Update package.json scripts
        node -e "
        const pkg = require('./package.json');
        pkg.main = 'src/index.js';
        pkg.scripts = {
            start: 'node src/index.js',
            dev: 'nodemon src/index.js',
            test: 'jest --coverage',
            build: 'echo No build step for Node.js'
        };
        require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
        " 2>/dev/null || true

        cat > src/index.js <<'JS'
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const rateLimit = require('express-rate-limit');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(helmet());
app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use(morgan('combined'));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, max: 100 }));

// Routes
app.get('/', (req, res) => {
    res.json({
        status: 'ok',
        message: 'API is running',
        version: process.env.npm_package_version || '1.0.0',
        timestamp: new Date().toISOString()
    });
});

app.get('/health', (req, res) => res.json({ status: 'healthy' }));

// 404
app.use('*', (req, res) => res.status(404).json({ error: 'Not found' }));

// Error handler
app.use((err, req, res, _next) => {
    console.error(err);
    res.status(500).json({ error: 'Internal server error' });
});

app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
module.exports = app;
JS

        cat > .env <<'ENV'
PORT=3000
NODE_ENV=development
ENV
        add_common_files .
        ;;

    python)
        log_step "Creating Python FastAPI project..."
        mkdir -p "$DEST"/{app/{routers,models,schemas},tests}
        cd "$DEST"

        cat > requirements.txt <<'REQ'
fastapi==0.109.0
uvicorn[standard]==0.27.0
python-dotenv==1.0.0
pydantic==2.5.3
httpx==0.26.0
pytest==7.4.4
pytest-asyncio==0.23.3
REQ

        cat > app/main.py <<'PY'
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager
import os

@asynccontextmanager
async def lifespan(app: FastAPI):
    print("Starting up...")
    yield
    print("Shutting down...")

app = FastAPI(
    title="API",
    version="1.0.0",
    lifespan=lifespan
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
async def root():
    return {"status": "ok", "message": "API is running"}

@app.get("/health")
async def health():
    return {"status": "healthy"}
PY

        cat > main.py <<'PY'
import uvicorn
import os

if __name__ == "__main__":
    uvicorn.run(
        "app.main:app",
        host="0.0.0.0",
        port=int(os.getenv("PORT", 8000)),
        reload=os.getenv("ENV", "development") == "development"
    )
PY

        cat > .env <<'ENV'
PORT=8000
ENV=development
ENV
        add_common_files .
        ;;

    java|spring-boot)
        log_step "Creating Spring Boot project..."
        mkdir -p "$DEST"
        cd "$DEST"
        # Download from Spring Initializr if curl available
        if command_exists curl; then
            curl -sL "https://start.spring.io/starter.zip\
?type=gradle-project\
&language=java\
&bootVersion=3.2.0\
&groupId=com.dnyftech\
&artifactId=$NAME\
&name=$NAME\
&dependencies=web,actuator,devtools" -o starter.zip 2>/dev/null && \
            unzip -q starter.zip && rm starter.zip 2>/dev/null || \
            log_warn "Could not download Spring Initializr template — create manually"
        fi
        add_common_files .
        ;;

    react)
        require node
        log_step "Creating React (Vite) project..."
        npm create vite@latest "$DEST" -- --template react
        cd "$DEST" && npm install
        add_common_files .
        ;;

    vue)
        require node
        log_step "Creating Vue 3 (Vite) project..."
        npm create vite@latest "$DEST" -- --template vue
        cd "$DEST" && npm install
        add_common_files .
        ;;

    *)
        log_error "Unknown template: $TEMPLATE"
        echo "Available templates: react-native, flutter, android, nodejs, python, java, react, vue"
        exit 1
        ;;
esac

ELAPSED=$(timer_elapsed)
echo ""
log_success "Project created in ${BOLD}$ELAPSED${RESET}"
log_info    "Directory : ${CYAN}$DEST${RESET}"
echo ""
echo -e "${BOLD}Next steps:${RESET}"
echo "  cd $DEST"
echo "  abp build . --target android --profile release"
echo "  abp build . --target android --sign --install"
echo ""
