#!/usr/bin/env bash
# DNYFappbuilder — Project Init Script v2.2.0
# Templates: react-native, flutter, android, nodejs, nodejs-ts,
#            python, django, java, react, vue, nextjs, svelte,
#            electron, go, pwa, rust

ABP_ROOT="${ABP_ROOT:-$HOME/dnyf-appbuilder}"
source "$ABP_ROOT/lib/common.sh"

NAME="${1:-myapp}"
TEMPLATE="${2:-react-native}"
DEST="${3:-./$NAME}"

[[ -d "$DEST" ]] && {
    log_error "Directory already exists: $DEST"
    exit 1
}

log_info "Creating project: ${BOLD}$NAME${RESET} (template: $TEMPLATE)"
timer_start

# ── Common files ───────────────────────────────────────────
add_common_files() {
    local dir="$1"
    cat > "$dir/.gitignore" << 'GIT'
.env
.env.*
*.keystore
*.jks
node_modules/
venv/
__pycache__/
*.pyc
.dart_tool/
build/
dist/
.gradle/
*.log
.DS_Store
.next/
.svelte-kit/
target/
GIT

    cat > "$dir/.editorconfig" << 'EC'
root = true
[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
EC

    cat > "$dir/README.md" << MD
# $NAME

Generated by [DNYFappbuilder](https://github.com/DNYFTETCH/DNYFappbuilder) v2.2.0

## Quick Start

\`\`\`bash
abp build . --target android --profile release --sign --install
\`\`\`

## Commands

\`\`\`bash
abp build .                    # Build project
abp build . --sign --install   # Build + sign + install to device
abp deploy railway             # Deploy to cloud
abp doctor                     # Check environment
\`\`\`
MD
}

# ── Templates ──────────────────────────────────────────────
case "$TEMPLATE" in

# ── React Native ──────────────────────────────────────────
    react-native)
        require node "pkg install nodejs"
        require npx  "comes with npm"
        log_step "Initializing React Native project..."
        npx @react-native-community/cli init "$NAME" --directory "$DEST" --skip-install
        cd "$DEST"
        npm install
        add_common_files .
        ;;

# ── Flutter ───────────────────────────────────────────────
    flutter)
        require flutter "https://flutter.dev"
        log_step "Creating Flutter project..."
        flutter create --project-name "$(echo "$NAME" | tr '-' '_')" "$DEST"
        add_common_files "$DEST"
        ;;

# ── Native Android (Kotlin) ───────────────────────────────
    android)
        log_step "Creating native Android (Kotlin) project..."
        local PKG="com.dnyftech.$(echo "$NAME" | tr '-' '_')"
        local PKG_PATH="$(echo "$PKG" | tr '.' '/')"
        mkdir -p "$DEST"
        cd "$DEST"
        mkdir -p "app/src/main/java/$PKG_PATH"
        mkdir -p "app/src/main/res/{layout,values,drawable,mipmap-hdpi,mipmap-xhdpi,mipmap-xxhdpi}"

        cat > settings.gradle.kts << GRADLE
pluginManagement {
    repositories { google(); mavenCentral(); gradlePluginPortal() }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories { google(); mavenCentral() }
}
rootProject.name = "$NAME"
include(":app")
GRADLE

        cat > build.gradle.kts << GRADLE
plugins {
    id("com.android.application") version "8.1.0" apply false
    id("org.jetbrains.kotlin.android") version "1.9.0" apply false
}
GRADLE

        cat > app/build.gradle.kts << GRADLE
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}
android {
    namespace = "$PKG"
    compileSdk = 34
    defaultConfig {
        applicationId = "$PKG"
        minSdk = 24
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
    }
    buildTypes {
        release {
            isMinifyEnabled = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions { jvmTarget = "1.8" }
    buildFeatures { viewBinding = true }
}
dependencies {
    implementation("androidx.core:core-ktx:1.12.0")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("com.google.android.material:material:1.10.0")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0")
}
GRADLE

        cat > "app/src/main/java/$PKG_PATH/MainActivity.kt" << KOTLIN
package $PKG

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
    }
}
KOTLIN

        cat > app/src/main/AndroidManifest.xml << XML
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:allowBackup="true"
        android:label="$NAME"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.AppCompat.DayNight.DarkActionBar">
        <activity android:name=".MainActivity" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>
XML

        cat > app/src/main/res/layout/activity_main.xml << XML
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="$NAME"
        android:textSize="24sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"/>
</androidx.constraintlayout.widget.ConstraintLayout>
XML

        echo "#!/bin/sh\ngradle \"\$@\"" > gradlew && chmod +x gradlew
        touch app/proguard-rules.pro
        add_common_files .
        ;;

# ── Node.js (JavaScript) ──────────────────────────────────
    nodejs)
        log_step "Creating Node.js Express API..."
        mkdir -p "$DEST"/{src/{routes,middleware,models},tests}
        cd "$DEST"

        cat > package.json << JSON
{
  "name": "$NAME",
  "version": "1.0.0",
  "description": "Node.js Express API — DNYFappbuilder",
  "main": "src/index.js",
  "scripts": {
    "start":  "node src/index.js",
    "dev":    "nodemon src/index.js",
    "test":   "jest --coverage",
    "build":  "echo 'No compile step — ready to run'"
  },
  "dependencies": {
    "express":            "^4.18.2",
    "cors":               "^2.8.5",
    "dotenv":             "^16.3.1",
    "helmet":             "^7.1.0",
    "morgan":             "^1.10.0",
    "express-rate-limit": "^7.1.5"
  },
  "devDependencies": {
    "nodemon": "^3.0.2",
    "jest":    "^29.7.0",
    "supertest":"^6.3.3"
  }
}
JSON

        cat > src/index.js << 'JS'
const express     = require('express');
const cors        = require('cors');
const helmet      = require('helmet');
const morgan      = require('morgan');
const rateLimit   = require('express-rate-limit');
require('dotenv').config();

const app  = express();
const PORT = process.env.PORT || 3000;

app.use(helmet());
app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use(morgan('combined'));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, max: 100 }));

app.get('/',       (req, res) => res.json({ status: 'ok', app: process.env.npm_package_name, version: process.env.npm_package_version }));
app.get('/health', (req, res) => res.json({ status: 'healthy', uptime: process.uptime() }));

app.use('*', (req, res)           => res.status(404).json({ error: 'Not found' }));
app.use((err, req, res, _next)    => { console.error(err); res.status(500).json({ error: 'Internal server error' }); });

app.listen(PORT, () => console.log(`✓ Server on port ${PORT}`));
module.exports = app;
JS

        cat > src/routes/index.js << 'JS'
const express = require('express');
const router  = express.Router();
router.get('/ping', (req, res) => res.json({ pong: true }));
module.exports = router;
JS

        cat > tests/app.test.js << 'JS'
const request = require('supertest');
const app     = require('../src/index');

test('GET / returns ok', async () => {
    const res = await request(app).get('/');
    expect(res.status).toBe(200);
    expect(res.body.status).toBe('ok');
});

test('GET /health returns healthy', async () => {
    const res = await request(app).get('/health');
    expect(res.status).toBe(200);
    expect(res.body.status).toBe('healthy');
});
JS

        cat > .env << 'ENV'
PORT=3000
NODE_ENV=development
ENV
        add_common_files .
        ;;

# ── Node.js TypeScript ────────────────────────────────────
    nodejs-ts)
        log_step "Creating Node.js TypeScript API..."
        mkdir -p "$DEST"/{src/{routes,middleware,types},tests}
        cd "$DEST"

        cat > package.json << JSON
{
  "name": "$NAME",
  "version": "1.0.0",
  "main": "dist/index.js",
  "scripts": {
    "start":  "node dist/index.js",
    "dev":    "ts-node-dev --respawn src/index.ts",
    "build":  "tsc",
    "test":   "jest --coverage"
  },
  "dependencies": {
    "express": "^4.18.2",
    "cors":    "^2.8.5",
    "dotenv":  "^16.3.1",
    "helmet":  "^7.1.0"
  },
  "devDependencies": {
    "typescript":      "^5.3.3",
    "@types/express":  "^4.17.21",
    "@types/cors":     "^2.8.17",
    "@types/node":     "^20.11.0",
    "ts-node-dev":     "^2.0.0",
    "jest":            "^29.7.0",
    "ts-jest":         "^29.1.1"
  }
}
JSON

        cat > tsconfig.json << 'TS'
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["ES2020"],
    "outDir": "dist",
    "rootDir": "src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist", "tests"]
}
TS

        cat > src/index.ts << 'TS'
import express, { Request, Response, NextFunction } from 'express';
import cors    from 'cors';
import helmet  from 'helmet';
import dotenv  from 'dotenv';
dotenv.config();

const app  = express();
const PORT = parseInt(process.env.PORT || '3000', 10);

app.use(helmet());
app.use(cors());
app.use(express.json());

app.get('/',       (_req: Request, res: Response) => res.json({ status: 'ok' }));
app.get('/health', (_req: Request, res: Response) => res.json({ status: 'healthy', uptime: process.uptime() }));

app.use((_err: Error, _req: Request, res: Response, _next: NextFunction) => {
    res.status(500).json({ error: 'Internal server error' });
});

app.listen(PORT, () => console.log(`✓ Server on port ${PORT}`));
export default app;
TS

        cat > .env << 'ENV'
PORT=3000
NODE_ENV=development
ENV
        add_common_files .
        ;;

# ── React (Vite) — fully scaffolded, no npm create needed ─
    react)
        log_step "Creating React + Vite project..."
        mkdir -p "$DEST"/src
        cd "$DEST"

        cat > package.json << JSON
{
  "name": "$NAME",
  "version": "0.0.1",
  "private": true,
  "type": "module",
  "scripts": {
    "dev":     "vite",
    "build":   "vite build",
    "preview": "vite preview",
    "test":    "vitest run"
  },
  "dependencies": {
    "react":     "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react":          "^18.2.55",
    "@types/react-dom":      "^18.2.19",
    "@vitejs/plugin-react":  "^4.2.1",
    "vite":                  "^5.1.0",
    "vitest":                "^1.2.2"
  }
}
JSON

        cat > vite.config.js << 'VITE'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: { port: 3000, open: true },
  build:  { outDir: 'dist', sourcemap: true }
})
VITE

        cat > index.html << HTML
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>$NAME</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
HTML

        cat > src/main.jsx << 'JSX'
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
JSX

        cat > src/App.jsx << 'JSX'
import { useState } from 'react'
import './App.css'

function App() {
  const [count, setCount] = useState(0)
  return (
    <div className="app">
      <h1>DNYFappbuilder ⚡ React</h1>
      <div className="card">
        <button onClick={() => setCount(c => c + 1)}>count is {count}</button>
        <p>Built with DNYFappbuilder v2.2.0</p>
      </div>
    </div>
  )
}

export default App
JSX

        cat > src/App.css << 'CSS'
.app { max-width: 1280px; margin: 0 auto; padding: 2rem; text-align: center; }
.app h1 { font-size: 2.5rem; line-height: 1.1; }
.card { padding: 2em; }
.card button {
  border-radius: 8px;
  border: 1px solid #646cff;
  padding: 0.6em 1.2em;
  font-size: 1em;
  cursor: pointer;
  background: #1a1a2e;
  color: #fff;
  transition: border-color 0.25s;
}
.card button:hover { border-color: #535bf2; }
CSS

        cat > src/index.css << 'CSS'
:root { font-family: Inter, system-ui, sans-serif; }
body { margin: 0; background: #0d1117; color: #e6edf3; }
CSS

        add_common_files .
        ;;

# ── Vue 3 (Vite) — fully scaffolded ──────────────────────
    vue)
        log_step "Creating Vue 3 + Vite project..."
        mkdir -p "$DEST"/src/{components,views,stores}
        cd "$DEST"

        cat > package.json << JSON
{
  "name": "$NAME",
  "version": "0.0.1",
  "private": true,
  "type": "module",
  "scripts": {
    "dev":     "vite",
    "build":   "vite build",
    "preview": "vite preview",
    "test":    "vitest run"
  },
  "dependencies": {
    "vue":       "^3.4.15",
    "vue-router":"^4.2.5",
    "pinia":     "^2.1.7"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.4",
    "vite":               "^5.1.0",
    "vitest":             "^1.2.2"
  }
}
JSON

        cat > vite.config.js << 'VITE'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue()],
  server: { port: 3000, open: true },
  build:  { outDir: 'dist', sourcemap: true }
})
VITE

        cat > index.html << HTML
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>$NAME</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
HTML

        cat > src/main.js << 'JS'
import { createApp } from 'vue'
import { createPinia } from 'pinia'
import App from './App.vue'

const app = createApp(App)
app.use(createPinia())
app.mount('#app')
JS

        cat > src/App.vue << 'VUE'
<script setup>
import { ref } from 'vue'
const count = ref(0)
</script>

<template>
  <div class="app">
    <h1>DNYFappbuilder ⚡ Vue</h1>
    <div class="card">
      <button @click="count++">count is {{ count }}</button>
      <p>Built with DNYFappbuilder v2.2.0</p>
    </div>
  </div>
</template>

<style>
body { margin: 0; background: #0d1117; color: #e6edf3; font-family: sans-serif; }
.app { max-width: 1280px; margin: 0 auto; padding: 2rem; text-align: center; }
.card button {
  border-radius: 8px; border: 1px solid #42b883; padding: 0.6em 1.2em;
  font-size: 1em; cursor: pointer; background: #1a1a2e; color: #fff;
}
.card button:hover { border-color: #33a06f; }
</style>
VUE

        add_common_files .
        ;;

# ── Next.js ───────────────────────────────────────────────
    nextjs)
        log_step "Creating Next.js App Router project..."
        mkdir -p "$DEST"/{app,public,components,lib}
        cd "$DEST"

        cat > package.json << JSON
{
  "name": "$NAME",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev":   "next dev",
    "build": "next build",
    "start": "next start",
    "lint":  "next lint"
  },
  "dependencies": {
    "next":     "14.1.0",
    "react":    "^18",
    "react-dom":"^18"
  },
  "devDependencies": {
    "@types/node":     "^20",
    "@types/react":    "^18",
    "@types/react-dom":"^18",
    "typescript":      "^5"
  }
}
JSON

        cat > next.config.mjs << 'NEXT'
/** @type {import('next').NextConfig} */
const nextConfig = {};
export default nextConfig;
NEXT

        cat > tsconfig.json << 'TS'
{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom","dom.iterable","esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{"name": "next"}],
    "paths": {"@/*": ["./*"]}
  },
  "include": ["next-env.d.ts","**/*.ts","**/*.tsx",".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
TS

        cat > app/layout.tsx << 'TSX'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: '$NAME',
  description: 'Built with DNYFappbuilder',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, background: '#0d1117', color: '#e6edf3', fontFamily: 'sans-serif' }}>
        {children}
      </body>
    </html>
  )
}
TSX

        cat > app/page.tsx << 'TSX'
export default function Home() {
  return (
    <main style={{ maxWidth: '1200px', margin: '0 auto', padding: '4rem 2rem', textAlign: 'center' }}>
      <h1>$NAME</h1>
      <p style={{ color: '#7d8590' }}>Built with DNYFappbuilder ⚡ Next.js 14</p>
    </main>
  )
}
TSX

        mkdir -p app/api/health
        cat > app/api/health/route.ts << 'TS'
import { NextResponse } from 'next/server'
export async function GET() {
  return NextResponse.json({ status: 'healthy', timestamp: new Date().toISOString() })
}
TS

        cat > .env.local << 'ENV'
NEXT_PUBLIC_APP_NAME=$NAME
ENV
        add_common_files .
        ;;

# ── Svelte (SvelteKit) ────────────────────────────────────
    svelte)
        log_step "Creating SvelteKit project..."
        mkdir -p "$DEST"/{src/{routes,lib/components},static}
        cd "$DEST"

        cat > package.json << JSON
{
  "name": "$NAME",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev":     "vite dev",
    "build":   "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@sveltejs/kit": "^2.0.0",
    "svelte":        "^4.2.7"
  },
  "devDependencies": {
    "@sveltejs/adapter-auto": "^3.0.0",
    "vite":                   "^5.0.3"
  },
  "type": "module"
}
JSON

        cat > svelte.config.js << 'SVELTE'
import adapter from '@sveltejs/adapter-auto';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: { adapter: adapter() }
};

export default config;
SVELTE

        cat > vite.config.js << 'VITE'
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [sveltekit()]
});
VITE

        cat > src/routes/+page.svelte << 'SVELTE'
<script>
  let count = 0;
</script>

<main>
  <h1>DNYFappbuilder ⚡ SvelteKit</h1>
  <div class="card">
    <button on:click={() => count++}>count is {count}</button>
    <p>Built with DNYFappbuilder v2.2.0</p>
  </div>
</main>

<style>
  main { max-width: 1280px; margin: 0 auto; padding: 2rem; text-align: center; }
  button {
    border-radius: 8px; border: 1px solid #ff3e00; padding: 0.6em 1.2em;
    font-size: 1em; cursor: pointer; background: #1a1a2e; color: #fff;
  }
  button:hover { border-color: #ff6240; }
</style>
SVELTE

        cat > src/routes/+layout.svelte << 'SVELTE'
<slot />
SVELTE

        add_common_files .
        ;;

# ── Electron ──────────────────────────────────────────────
    electron)
        log_step "Creating Electron desktop app..."
        mkdir -p "$DEST"/src
        cd "$DEST"

        cat > package.json << JSON
{
  "name": "$NAME",
  "version": "1.0.0",
  "description": "Electron desktop app — DNYFappbuilder",
  "main": "src/main.js",
  "scripts": {
    "start":   "electron .",
    "build":   "electron-builder",
    "pack":    "electron-builder --dir",
    "dist":    "electron-builder --publish=never"
  },
  "dependencies": {},
  "devDependencies": {
    "electron":         "^28.2.0",
    "electron-builder": "^24.9.1"
  },
  "build": {
    "appId":   "com.dnyftech.$NAME",
    "productName": "$NAME",
    "linux":   { "target": "AppImage" },
    "win":     { "target": "nsis" },
    "mac":     { "target": "dmg" }
  }
}
JSON

        cat > src/main.js << 'JS'
const { app, BrowserWindow, ipcMain } = require('electron')
const path = require('path')

function createWindow() {
  const win = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      preload:     path.join(__dirname, 'preload.js'),
      nodeIntegration: false,
      contextIsolation: true
    }
  })
  win.loadFile('src/index.html')
}

app.whenReady().then(createWindow)
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit() })
app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) createWindow() })
JS

        cat > src/preload.js << 'JS'
const { contextBridge, ipcRenderer } = require('electron')
contextBridge.exposeInMainWorld('electronAPI', {
  platform: process.platform,
  version:  process.versions.electron
})
JS

        cat > src/index.html << HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="Content-Security-Policy" content="default-src 'self'">
  <title>$NAME</title>
  <style>
    body { margin: 0; background: #0d1117; color: #e6edf3; font-family: sans-serif;
           display: flex; align-items: center; justify-content: center; height: 100vh; flex-direction: column; }
    h1 { font-size: 2rem; }
    p  { color: #7d8590; }
  </style>
</head>
<body>
  <h1>DNYFappbuilder ⚡ Electron</h1>
  <p>$NAME — Desktop App</p>
  <p id="info"></p>
  <script>
    document.getElementById('info').textContent =
      'Platform: ' + window.electronAPI?.platform + ' · Electron ' + window.electronAPI?.version;
  </script>
</body>
</html>
HTML

        add_common_files .
        ;;

# ── Python FastAPI ────────────────────────────────────────
    python)
        log_step "Creating Python FastAPI project..."
        mkdir -p "$DEST"/{app/{routers,models,schemas,services},tests}
        cd "$DEST"

        cat > requirements.txt << 'REQ'
fastapi==0.109.0
uvicorn[standard]==0.27.0
python-dotenv==1.0.0
pydantic==2.5.3
httpx==0.26.0
sqlalchemy==2.0.25
alembic==1.13.1
pytest==7.4.4
pytest-asyncio==0.23.3
REQ

        cat > app/__init__.py << 'PY'
PY

        cat > app/main.py << 'PY'
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager
import os

@asynccontextmanager
async def lifespan(app: FastAPI):
    print("✓ Starting up")
    yield
    print("✓ Shutting down")

app = FastAPI(
    title="API",
    version="1.0.0",
    description="Built with DNYFappbuilder",
    lifespan=lifespan
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/", tags=["root"])
async def root():
    return {"status": "ok", "message": "API is running", "version": "1.0.0"}

@app.get("/health", tags=["health"])
async def health():
    return {"status": "healthy"}
PY

        cat > main.py << 'PY'
import uvicorn, os
if __name__ == "__main__":
    uvicorn.run(
        "app.main:app",
        host="0.0.0.0",
        port=int(os.getenv("PORT", 8000)),
        reload=os.getenv("ENV", "development") == "development"
    )
PY

        cat > tests/__init__.py << 'PY'
PY

        cat > tests/test_main.py << 'PY'
import pytest
from httpx import AsyncClient
from app.main import app

@pytest.mark.asyncio
async def test_root():
    async with AsyncClient(app=app, base_url="http://test") as ac:
        res = await ac.get("/")
    assert res.status_code == 200
    assert res.json()["status"] == "ok"

@pytest.mark.asyncio
async def test_health():
    async with AsyncClient(app=app, base_url="http://test") as ac:
        res = await ac.get("/health")
    assert res.status_code == 200
PY

        cat > .env << 'ENV'
PORT=8000
ENV=development
DATABASE_URL=sqlite:///./app.db
ENV
        add_common_files .
        ;;

# ── Django ────────────────────────────────────────────────
    django)
        log_step "Creating Django REST API project..."
        mkdir -p "$DEST"/{config,api/{migrations},static,media,tests}
        cd "$DEST"

        cat > requirements.txt << 'REQ'
Django==4.2.10
djangorestframework==3.14.0
django-cors-headers==4.3.1
python-dotenv==1.0.0
gunicorn==21.2.0
whitenoise==6.6.0
pytest-django==4.7.0
REQ

        cat > manage.py << 'PY'
#!/usr/bin/env python
import os, sys
def main():
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError("Couldn't import Django.") from exc
    execute_from_command_line(sys.argv)
if __name__ == '__main__':
    main()
PY

        cat > config/__init__.py << 'PY'
PY

        cat > config/settings.py << 'PY'
from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = os.getenv('SECRET_KEY', 'dev-secret-key-change-in-production')
DEBUG      = os.getenv('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

INSTALLED_APPS = [
    'django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes',
    'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles',
    'rest_framework', 'corsheaders', 'api',
]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]
ROOT_URLCONF = 'config.urls'
DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': BASE_DIR / 'db.sqlite3'}}
STATIC_URL  = '/static/'
CORS_ALLOW_ALL_ORIGINS = True
REST_FRAMEWORK = {'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer']}
PY

        cat > config/urls.py << 'PY'
from django.urls import path, include
urlpatterns = [
    path('api/', include('api.urls')),
]
PY

        cat > api/__init__.py << 'PY'
PY

        cat > api/views.py << 'PY'
from rest_framework.decorators import api_view
from rest_framework.response import Response

@api_view(['GET'])
def root(request):
    return Response({'status': 'ok', 'message': 'API is running'})

@api_view(['GET'])
def health(request):
    return Response({'status': 'healthy'})
PY

        cat > api/urls.py << 'PY'
from django.urls import path
from . import views
urlpatterns = [
    path('',        views.root,   name='root'),
    path('health/', views.health, name='health'),
]
PY

        cat > .env << 'ENV'
SECRET_KEY=change-me-in-production
DEBUG=True
ALLOWED_HOSTS=*
PORT=8000
ENV
        add_common_files .
        ;;

# ── Go ────────────────────────────────────────────────────
    go)
        log_step "Creating Go HTTP server..."
        mkdir -p "$DEST"/{cmd/server,internal/{handlers,middleware},pkg}
        cd "$DEST"
        local MODULE="github.com/dnyftech/$NAME"

        cat > go.mod << MOD
module $MODULE

go 1.21

require (
    github.com/go-chi/chi/v5 v5.0.11
)
MOD

        cat > cmd/server/main.go << 'GO'
package main

import (
    "encoding/json"
    "fmt"
    "log"
    "net/http"
    "os"
    "time"

    "github.com/go-chi/chi/v5"
    "github.com/go-chi/chi/v5/middleware"
)

func main() {
    port := os.Getenv("PORT")
    if port == "" { port = "8080" }

    r := chi.NewRouter()
    r.Use(middleware.Logger)
    r.Use(middleware.Recoverer)
    r.Use(middleware.Timeout(30 * time.Second))

    r.Get("/", func(w http.ResponseWriter, r *http.Request) {
        w.Header().Set("Content-Type", "application/json")
        json.NewEncoder(w).Encode(map[string]string{"status": "ok", "message": "API is running"})
    })

    r.Get("/health", func(w http.ResponseWriter, r *http.Request) {
        w.Header().Set("Content-Type", "application/json")
        json.NewEncoder(w).Encode(map[string]string{"status": "healthy"})
    })

    fmt.Printf("✓ Server on port %s\n", port)
    log.Fatal(http.ListenAndServe(":"+port, r))
}
GO

        cat > Makefile << 'MAKE'
build:
	go build -o bin/server ./cmd/server

run:
	go run ./cmd/server

test:
	go test ./...

tidy:
	go mod tidy
MAKE

        cat > .env << 'ENV'
PORT=8080
ENV=development
ENV
        add_common_files .
        ;;

# ── PWA (Progressive Web App) ─────────────────────────────
    pwa)
        log_step "Creating Progressive Web App..."
        mkdir -p "$DEST"/{src,public,icons}
        cd "$DEST"

        cat > package.json << JSON
{
  "name": "$NAME",
  "version": "1.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev":     "vite",
    "build":   "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "workbox-window": "^7.0.0"
  },
  "devDependencies": {
    "vite":          "^5.1.0",
    "vite-plugin-pwa":"^0.19.0"
  }
}
JSON

        cat > vite.config.js << 'VITE'
import { defineConfig } from 'vite'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  plugins: [
    VitePWA({
      registerType: 'autoUpdate',
      manifest: {
        name: 'DNYFappbuilder PWA',
        short_name: 'ABP PWA',
        theme_color: '#6c63ff',
        background_color: '#080b10',
        display: 'standalone',
        icons: [
          { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
          { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' }
        ]
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,png,svg,ico}']
      }
    })
  ]
})
VITE

        cat > index.html << HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta name="theme-color" content="#6c63ff"/>
  <link rel="manifest" href="/manifest.json"/>
  <title>$NAME</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      background: #080b10; color: #e6edf3;
      font-family: 'JetBrains Mono', monospace;
      display: flex; align-items: center; justify-content: center;
      min-height: 100vh; flex-direction: column; gap: 1rem;
    }
    h1 { font-size: 2rem; color: #6c63ff; }
    p  { color: #7d8590; font-size: 0.9rem; }
    #status { color: #00d4aa; font-size: 0.8rem; }
  </style>
</head>
<body>
  <h1>$NAME</h1>
  <p>Progressive Web App — DNYFappbuilder</p>
  <p id="status">Checking service worker...</p>
  <script type="module" src="/src/main.js"></script>
</body>
</html>
HTML

        cat > src/main.js << 'JS'
if ('serviceWorker' in navigator) {
  navigator.serviceWorker.register('/sw.js')
    .then(() => { document.getElementById('status').textContent = '✓ Offline ready'; })
    .catch(() => { document.getElementById('status').textContent = 'Service worker unavailable'; });
}
JS

        add_common_files .
        ;;

# ── Java / Spring Boot ────────────────────────────────────
    java|spring-boot)
        log_step "Creating Spring Boot project..."
        mkdir -p "$DEST"
        cd "$DEST"
        if command -v curl &>/dev/null; then
            curl -sL "https://start.spring.io/starter.zip\
?type=gradle-project\
&language=java\
&bootVersion=3.2.0\
&groupId=com.dnyftech\
&artifactId=$NAME\
&name=$NAME\
&dependencies=web,actuator,devtools" -o starter.zip 2>/dev/null && \
            unzip -q starter.zip && rm starter.zip 2>/dev/null || \
            log_warn "Spring Initializr unavailable — add dependencies manually"
        fi
        add_common_files .
        ;;

# ── Rust ──────────────────────────────────────────────────
    rust)
        log_step "Creating Rust web server..."
        require cargo "pkg install rust / https://rustup.rs"
        cargo init "$DEST" --name "$NAME"
        cd "$DEST"

        cat > Cargo.toml << TOML
[package]
name    = "$NAME"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde     = { version = "1", features = ["derive"] }
serde_json= "1"
tokio     = { version = "1", features = ["full"] }
dotenv    = "0.15"
TOML

        cat > src/main.rs << 'RUST'
use actix_web::{get, web, App, HttpResponse, HttpServer, Responder};
use serde_json::json;

#[get("/")]
async fn root() -> impl Responder {
    HttpResponse::Ok().json(json!({"status": "ok", "message": "API is running"}))
}

#[get("/health")]
async fn health() -> impl Responder {
    HttpResponse::Ok().json(json!({"status": "healthy"}))
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    let port = std::env::var("PORT").unwrap_or_else(|_| "8080".to_string());
    let addr = format!("0.0.0.0:{}", port);
    println!("✓ Server on {}", addr);
    HttpServer::new(|| {
        App::new()
            .service(root)
            .service(health)
    })
    .bind(&addr)?
    .run()
    .await
}
RUST

        cat > .env << 'ENV'
PORT=8080
RUST_LOG=info
ENV
        add_common_files .
        ;;

    *)
        log_error "Unknown template: $TEMPLATE"
        echo ""
        echo "Available templates:"
        echo "  Mobile    : react-native, flutter, android"
        echo "  Frontend  : react, vue, nextjs, svelte, pwa"
        echo "  Backend   : nodejs, nodejs-ts, python, django, go, java, rust"
        echo "  Desktop   : electron"
        exit 1
        ;;
esac

ELAPSED=$(timer_elapsed)
echo ""
log_success "Project created in ${BOLD}$ELAPSED${RESET}"
log_info    "Directory : ${CYAN}$DEST${RESET}"
log_info    "Template  : ${CYAN}$TEMPLATE${RESET}"
echo ""
echo -e "${BOLD}Next steps:${RESET}"
echo "  cd $DEST"
case "$TEMPLATE" in
    react|vue|nextjs|svelte|pwa)
        echo "  npm install && npm run dev"
        echo "  abp build . --profile production"
        ;;
    python|django)
        echo "  python3 -m venv venv && source venv/bin/activate"
        echo "  pip install -r requirements.txt"
        echo "  abp build . && abp deploy railway"
        ;;
    go)
        echo "  go mod tidy && go run ./cmd/server"
        echo "  abp build . && abp deploy railway"
        ;;
    rust)
        echo "  cargo run"
        echo "  abp build . && abp deploy docker"
        ;;
    electron)
        echo "  npm install && npm start"
        echo "  npm run build   # Package desktop app"
        ;;
    *)
        echo "  abp build . --target android --profile release --sign --install"
        ;;
esac
echo ""
